### ISSUE TITLE
Did not find the .buildinfo file in debian/files

### ISSUE THREAD

**Issue by r4sas** [jtdor/build-deb-action#3]
Hello.
I'm using your action to build testing packages for [our project](https://github.com/PurpleI2P/i2pd). Since yesterday, when 1.6.0 was released, action started failing at artifacts moving:

`Did not find the .buildinfo file in debian/files at /github/action/scripts/move_artifacts line 35.`

Example run: https://github.com/PurpleI2P/i2pd/actions/runs/4247105073/jobs/7384748674#step:3:1311
Workflow: https://github.com/PurpleI2P/i2pd/actions/runs/4247105073/workflow

Switching back to 1.5.0 [fixes issue](https://github.com/PurpleI2P/i2pd/actions/runs/4247159275/jobs/7384866759).
Any ideas? Thanks.

**Comment by jtdor** [comment]
Hi @r4sas,
thanks for the report and sorry about the inconvenience.

From a quick look at my changes, I used an incorrect regex to find the name of the .buildinfo file. The name of your package as built from the workflow does contain a `+`, which this regex (wrongly) does not accept.

That's easily fixable, will do that tomorrow and release a new version.

**Comment by r4sas** [comment]
FYI, same was when there was no `+` with previous version of workflow: https://github.com/PurpleI2P/i2pd/actions/runs/4246988979/workflow

**Comment by jtdor** [comment]
> FYI, same was when there was no `+` with previous version of workflow: https://github.com/PurpleI2P/i2pd/actions/runs/4246988979/workflow

You are right, the error affected any package name and version that contained anything besides `a-z`, `0-9` and `_`. The workflow you linked contained a `-` which unfortunately also made it fail.

Thanks again for the report. Its fixed now with [version 1.6.1](/jtdor/build-deb-action/releases/tag/v1.6.1).

For reference: This was bug introduced with version 1.6.0 and 8f94178.

**Comment by r4sas** [comment]
Thank you!

**Comment by r4sas** [comment]
btw, example with `before-build-hook` is incorrect, because 
1. git is not installs with devscripts
2. git would reject work with error `fatal: detected dubious ownership in repository at '/github/workspace'`

`before-build-hook: debchange --controlmaint --local="+$(git describe --tags)" "CI build"`

**Comment by jtdor** [comment]
Also thanks for these two hints, @r4sas. Feel free to also open a separate issue for such observations next time.

I added the forgotten dependency to the example and also simplified—well, enabled—the usage of `git` in the before-build-hook in version [1.7.0](https://github.com/jtdor/build-deb-action/releases/tag/v1.7.0).
